# Generated by Django 5.2.6 on 2025-10-25 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('copyright_text', models.TextField(blank=True)),
                ('spatial_reference', models.IntegerField(blank=True, null=True)),
                ('full_extent', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service ArcGIS',
                'verbose_name_plural': 'Services ArcGIS',
                'db_table': 'arcgis_services',
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('geometry_type', models.CharField(max_length=50)),
                ('display_field', models.CharField(blank=True, max_length=100)),
                ('spatial_reference', models.IntegerField(blank=True, null=True)),
                ('extent', models.JSONField(blank=True, default=dict)),
                ('fields_definition', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='ogsl.service')),
            ],
            options={
                'verbose_name': 'Layer ArcGIS',
                'verbose_name_plural': 'Layers ArcGIS',
                'db_table': 'arcgis_layers',
                'ordering': ['service', 'layer_id'],
                'unique_together': {('service', 'layer_id')},
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('site_name', models.CharField(blank=True, max_length=255)),
                ('geometry_type', models.CharField(max_length=50)),
                ('geometry_data', models.JSONField(blank=True, default=dict)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='ogsl.layer')),
            ],
            options={
                'verbose_name': 'Feature ArcGIS',
                'verbose_name_plural': 'Features ArcGIS',
                'db_table': 'arcgis_features',
                'indexes': [models.Index(fields=['layer', 'object_id'], name='arcgis_feat_layer_i_42a687_idx'), models.Index(fields=['site_name'], name='arcgis_feat_site_na_a7063a_idx')],
                'unique_together': {('layer', 'object_id')},
            },
        ),
    ]
