# Generated by Django 5.2.7 on 2025-10-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogsl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
