# Generated by Django 5.2.7 on 2025-10-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogsl', '0002_alter_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='layer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
